#!/usr/bin/env python3
import argparse

def main():
    parser = argparse.ArgumentParser(prog='pvm', description='python version manager')
    _register_commands(parser)

    args = parser.parse_args()
    _execute_commands(args)


def _execute_commands(args: argparse.Namespace):
    if args.command == 'use':
        print('Hello world')
    elif args.command == 'install':
        print('Installing version:', args.version)


def _register_commands(parser: argparse.ArgumentParser):
    parser.add_argument('--version', '-V', action='version', version='1.00', help='Version of PVM installed')
    subparsers = parser.add_subparsers(dest='command', required=True)
    _register_subcommands(subparsers)


def _register_subcommands(subparsers: argparse._SubParsersAction):
    use_parser = subparsers.add_parser('use', help='Select Python version')
    use_parser.add_argument('python version', help='Version to use (e.g. 3.12)')

    subparsers.add_parser('list', help='List installed Python versions')

    install_parser = subparsers.add_parser('install', help='Install a new Python version')
    install_parser.add_argument('python version', help='Version to install (e.g. 3.12)')


if __name__ == '__main__':
    main()
