#!/usr/bin/env python3
import argparse

def main():
    parser = argparse.ArgumentParser(prog='pvm', description='python version manager')
    _register_commands(parser)

    args = parser.parse_args()
    _execute_commands(args)


def _execute_commands(args: argparse.Namespace):
    if args.command == 'use':
        print('Hello world')


def _register_commands(parser: argparse.ArgumentParser):
    parser.add_argument('--version', '-V', action='version', version='1.00', help='Version of PVM installed')
    subparsers = parser.add_subparsers(dest='command', required=True)

    use_parser = subparsers.add_parser('use', help='Select Python version')
    use_parser.add_argument('version', help='Version to use (e.g. 3.12)')

if __name__ == '__main__':
    main()
